eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
server:
  port: 8002

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/one-meter/config-center
          searchPaths: config
      label: master
  application:
    name: config-server